services:
  hawkbot:
    build: .
    container_name: hawkbot
    restart: on-failure
    ports:
        - "${WEB_UI_PORT}:6969"
    volumes:
      - ./user_data:/src/user_data
      - ./logs:/src/logs
      - ./pyarmor.rkey:/src/pyarmor.rkey
      - ./data:/src/data
    logging:
      options:
        max-size: 2048m
    command: >
      python trade.py -a ${BOT_ACCOUNT} ${BOT_PARAMS}